const CLOUDINARY_CLOUD_NAME = process.env.REACT_APP_CLOUDINARY_CLOUD_NAME;
const CLOUDINARY_PRESENT_NAME = process.env.REACT_APP_CLOUDINARY_PRESENT_NAME;

export { CLOUDINARY_CLOUD_NAME, CLOUDINARY_PRESENT_NAME };